<?php
/**
 * Infographic default template
 *
 * @param string $message       String containing the message which is diplayed on testimonial.
 * @param array  $image         Array of data about image - id, url, sizes etc.
 * @param string $name          String containing the name used in testimonial.
 * @param string $designation   String containing the designation used in testimonial.
 * @param string $logo          Array of data about logo used in testimonial - id, url, sizes etc.
 * @param string $url            String containing the profile url used in testimonial.
 *
 * @example Usage
 * Component::render('InfoGraphic/GraphicFold');
 * @endexample
 */

use InstaWP\TemplateSystem\Component\Component;
?>

<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<script src="https://unpkg.com/@lottiefiles/lottie-interactivity@latest/dist/lottie-interactivity.min.js"></script>
<div id="infoGraphic" class="fp-section-content">
  <section class="fp-section info-graphic-section info-graphic-section-1" id="info-graphic-section-1">
      <div class="container">
          <div class="row">
              <div class="col-12 pc-text-center">
                  <div class="info-reset-inner-container">
                      <div class="info-header-content">
                        <h2>2021 trends <br> in digital advertising</h2>
                        <p>We surveyed  1,440  marketers to discover emerging digital advertising trends.<br>What we found might surprise you.</p>
                      </div>
                      <div class="lottieContainer" id="lottieContainer1">
                        <lottie-player id="firstLottie" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_1.json" 
                                      background="transparent" speed="1" autoplay loop>
                        </lottie-player>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-2" id="info-graphic-section-2">
      <div class="container">
          <div class="row">
              <div class="col-12 pc-text-center">
                  <div class="info-header-content">
                      <h3>A shift from traditional to digital</h3>
                      <p>Meeting your customers where they are is important – and due to the pandemic, that’s online.<br>
                          Ad spend is being pulled away from traditional and being pushed into digital.</p>
                  </div>
                  <div class="lottieContainer" id="lottieContainer2">
                      <lottie-player id="secondLottie" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_2.json" 
                                    background="transparent" speed="1" autoplay loop>
                      </lottie-player>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-3" id="info-graphic-section-3">
      <div class="container">
          <div class="row">
              <div class="col-md-5 pc-self-align">
                  <div class="info-header-content">
                      <h3>Digital budgets are increasing too.</h3>
                      <h5>33%</h5>
                      <p>of marketers expect their digital budgets to increase.</p>
                  </div>
              </div>
              <div class="col-md-7">
                  <div class="lottieContainer" id="lottieContainer3">
                      <lottie-player id="thirdLottie" class="lottie-graphic-right" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_3.json" 
                                    background="transparent" speed="1" autoplay>
                      </lottie-player>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-4" id="info-graphic-section-4">
      <div class="container">
          <div class="row">
              <div class="col-12 pc-text-center pc-self-align">
                <div class="info-header-content">
                      <h3>Utilization of Multiple Platforms</h3>
                      <p>According to marketers, Google and Facebook remain the top digital advertising platforms in <br> terms of usage and performance. Instagram doesn’t lag far behind. </p>
                </div>
                      <div class="pc-multiplatforms">
                        <div class="pc-multiplatforms-text pc-multiplatforms-top">
                          <h5>According to marketers, <span>Google</span> and <span>Facebook</span> remain the top digital advertising platforms in terms of usage and performance. </h5> </div>
                        <div class="pc-multiplatforms-text pc-multiplatforms-middle">
                          <h5><span>Instagram</span> <br> doesn’t lag far behind. </h5> </div>
                        <div class="pc-multiplatforms-text pc-multiplatforms-bottom">
                        <h5>25 %of those surveyed plan to use <span>TikTok</span> in 2021, nearly tripling from its current 14% utilization. </h5>
                        </div>
                        <div class="lottieContainer" id="lottieContainer4">
                          <lottie-player id="fourthLottie" class="lottie-graphic-left" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_4.json" 
                                        background="transparent" speed="1" autoplay>
                          </lottie-player>
                        </div>
                      </div>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-5" id="info-graphic-section-5">
      <div class="container">
          <div class="row">
              <div class="col-12 pc-text-center">
                  <div class="info-header-content">
                    <h3>Improvement in Digital Ad Programs</h3>
                  </div>
                  <div class="lottieContainer" id="lottieContainer5">
                      <lottie-player id="fifthLottie" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_5.json" 
                                    background="transparent" speed="1" autoplay>
                      </lottie-player>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-6" id="info-graphic-section-6">
      <div class="container">
          <div class="row info-reset-inner-container-2">
              <div class="col-md-6 pc-self-align info-mob-order-1">
                <div class="lottieContainer" id="lottieContainer6">
                    <lottie-player id="sixthLottie" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_6.json" 
                                    background="transparent" speed="1" autoplay>
                      </lottie-player>
                </div>
              </div>
              <div class="col-md-6 pc-self-align info-mob-order-2">
                <div class="info-header-content">
                  <h2>80%</h2>
                  <p>think their current ad programs are successful. </p>
                  <h2>95%</h2>
                  <p>see a problem with low conversion rates.</p>
                </div>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-7" id="info-graphic-section-7">
      <div class="container">
          <div class="row info-reset-inner-container-2">
              <div class="col-md-5 pc-self-align info-reset-bottom-margin info-mob-order-1">
                  <div class="info-header-content">
                    <h2>23%</h2>
                    <p>still optimize their campaigns for clicks  not <br>pre or post-click experiences</p>  
                  </div>
              </div>
              <div class="col-md-7 pc-text-center pc-self-align info-mob-order-2">
                <div class="lottieContainer" id="lottieContainer7">
                    <lottie-player id="seventhLottie" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_7.json" 
                                    background="transparent" speed="1" autoplay >
                      </lottie-player>
                </div>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-8" id="info-graphic-section-8">
      <div class="container">
          <div class="row">
              <div class="col-12 pc-text-center">
                <div class="info-header-content">
                  <h3>Improvement in Digital Ad Programs </h3>
                </div>
              </div>
          </div>
          <div class="row info-reset-inner-container-2">
              <div class="col-md-6 pc-self-align info-mob-order-1">
                <div class="info-content-area">
                  <h4>Across the board,<br>their main focuses are: </h4>
                  <ul>
                    <li>-increasing conversion rates,  </li>
                    <li>-growing return on ad spend,  </li>
                    <li>-enhancing targeting and segmentation  </li>
                  </ul>
                </div>
              </div>
              <div class="col-md-6 pc-text-center pc-self-align info-mob-order-2">
                <div class="lottieContainer" id="lottieContainer8">
                    <lottie-player id="eightLottie" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_8.json" 
                                    background="transparent" speed="1" autoplay >
                      </lottie-player>
                </div>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-9" id="info-graphic-section-9">
      <div class="container">
          <div class="row">
              <div class="col-12 pc-text-center">
                  <div class="info-header-content">
                    <h3>Use of Tech-Enabled Services </h3>
                  </div>
              </div>
          </div>
          <div class="row info-reset-inner-container">
              <div class="col-md-7 pc-text-center pc-self-align">
                    <lottie-player id="ninethLottie" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_9.json" 
                                    background="transparent" speed="1" autoplay >
                      </lottie-player>
              </div>
              <div class="col-md-5 pc-self-align">
                <div class="info-header-content">
                  <p>Those using tech-enabled services to <br> accomplish their digital advertising goals <br>were </p>
                  <h2>4.4 times <br>more likely</h2>
                  <p>than those relying on in-house or agency services to say they’re very satisfied with their conversion rates.</p>
                  </div>
              </div>
              
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-10" id="info-graphic-section-10">
      <div class="container">
          <div class="row">
              <div class="col-12 pc-text-center">
                  <div class="info-header-content">
                      <h3>Higher Conversions Start Here</h3>
                      <p>Postclick is a tech-enabled service combining the industry’s only post-click automation platform <br>with a team of conversion experts – giving you greater conversions. </p>
              </div>
                      <lottie-player id="tenthLottie" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_10.json" 
                                    background="transparent" speed="1" autoplay >
                      </lottie-player>
              </div>
          </div>
      </div>
  </section>
  <section class="fp-section info-graphic-section info-graphic-section-11" id="info-graphic-section-11">
      <div class="container">
          <div class="row">
              <div class="col-md-4 pc-text-center lattoie-roas-col lattoie-roas-col-1">
                <h6>Increase ROAS by 25% or more</h6>
                <p>Improved ad-to-page relevancy <br>with a higher CVR</p>
                    <div class="lattoie-roas-wrapper lattoie-mobile-only">
                        <lottie-player id="eleventhLottie_1_mob" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_11_1.json" 
                                        background="transparent" speed="1" autoplay loop>
                        </lottie-player>
                    </div>
              </div>
              <div class="col-md-4 pc-text-center lattoie-roas-col lattoie-roas-col-2">
                <h6>Lower your CPC by up to 50%</h6>
                <p>Increased Quality Score <br>and landing page relevance</p>
                    <div class="lattoie-roas-wrapper lattoie-mobile-only">
                        <lottie-player id="eleventhLottie_2_mob" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_11_2.json" 
                                        background="transparent" speed="1" autoplay loop>
                        </lottie-player>
                    </div>
              </div>
              <div class="col-md-4 pc-text-center lattoie-roas-col lattoie-roas-col-3">
                <h6>Save $500k+ annually</h6>
                <p>Decreased spend on resources <br>and scalability efforts</p>
                    <div class="lattoie-roas-wrapper lattoie-mobile-only">
                        <lottie-player id="eleventhLottie_3_mob" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_11_3.json" 
                                        background="transparent" speed="1" autoplay loop>
                        </lottie-player>
                    </div>
              </div>
          </div>
          <div class="row lattoie-roas-row lattoie-desktop-only">
               <div class="col-md-4 pc-text-center lattoie-roas-section">
                    <div class="lattoie-roas-wrapper">
                        <lottie-player id="eleventhLottie_1" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_11_1.json" 
                                        background="transparent" speed="1" autoplay loop>
                        </lottie-player>
                    </div>
              </div>
              <div class="col-md-4 pc-text-center lattoie-roas-section">
                <div class="lattoie-roas-wrapper">
                      <lottie-player id="eleventhLottie_2" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_11_2.json" 
                                    background="transparent" speed="1" autoplay loop>
                      </lottie-player>
                </div>
              </div>
              <div class="col-md-4 pc-text-center lattoie-roas-section">
                <div class="lattoie-roas-wrapper">
                      <lottie-player id="eleventhLottie_3" class="lottie-graphic-center" src="/wp-content/themes/postclick/src/Components/InfoGraphic/GraphicFold/LottieAnimations/animation_11_3.json" 
                                    background="transparent" speed="1" autoplay loop>
                      </lottie-player>
                </div>
              </div>
          </div>
          <div class="row info-graphic-cta" id="info-graphic-cta">
              <div class="col-12 pc-text-center">
                  <?php
                          Component::render(
                                        'Generic/Button',
                                        [
                                            'button' => [
                                                'class' => 'pc-button-medium pc-button-full pc-button-white',
                                                'type' => 'outline',
                                                'text' => 'Get started',
                                                'url' => '/lets-talk',
                                                'id'  => 'pc-info-graphic-cta'
                                            ]
                                        ]
                                    ); 
                    ?>
                </div>
          </div>
      </div>  
  </section>
  <section class="fp-auto-height fp-section " id="info_graphic_footer">
    <?php Component::render('Generic/Footer'); ?>
  </section>
</div>