<?php 
use Postclick\Helpers\CoreHelper;
if(isset($bannerLogo)):?>
<table style="background-color:#000;width:100%; height:100%; " cellspacing="2" cellpadding="0">
   <tr>
      <td>
         <table style="background-color:#000; height:800px; " cellspacing="0" cellpadding="0" style="width:100%;">
            <tr>
               <td style="background-color:#000; height:800px; " valign="middle">
                  <table  cellspacing="0" cellpadding="20" style="width:100%;">
                     <tr>
                        <td style="background-color:#000; vertical-align: middle; " valign="middle"><br><br>
                           <img src="<?= CoreHelper::getImageOriginalPath($bannerLogo['text_with_image_image']['id'] ?? null) ?>" alt="<?= esc_html($bannerLogo['text_with_image_image']['alt'] ?? ''); ?>" border="0" />
                        </td>
                     </tr>
                     <tr>
                     <?php 
                     $landingUrl =  preg_replace('/((^https?:\/\/)?(www\.)?)|(\/$)/', '', trim($content['landing_url']));
                     $domain = explode('/', $landingUrl);
                     ?>
                        <td color="white" style="font-family:helvetica;font-weight:bold;font-size:55px;line-height:55px; color:#ffffff;"><?php echo $bannerLogo['title'].' '.$domain[0] ?? ''; ?></td>
                     </tr>
                     <tr>
                        <td color="white" style="font-family:helvetica;font-weight:bold;font-size:16px;line-height:18px; color:#ffffff;"><?php echo $content['landing_url'] ?? ''; ?> </td>
                     </tr>
                  </table>
               </td>
            </tr>
         </table>
      </td>
   </tr>
</table>
<?php endif;?>